apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.mysql
  version: v1
  metadata:
  - name: connectionString
    value: "printer:123qwe!@#@tcp(rm-wz9f1jcr5466b42415o.mysql.rds.aliyuncs.com:3306)/?allowNativePasswords=true"
  - name: schemaName
    value: "printerdevtestw"
  - name: tableName
    value: "statestore"
  - name: actorStateStore
    value: "true"